const FETCHED_RESULTS = "FETCHED_RESULTS"
const FETCHED_DATA = "FETCHED_DATA"
const FETCHED_ALBUMS = "FETCHED_ALBUMS"
const ADD_ALBUM = "ADD_ALBUM"
const LOADING = "LOADING"
const CLOSE_MODAL = "CLOSE_MODAL"
const UPDATE_ALBUM = "UPDATE_ALBUM"
const DELETE_ALBUM = "DELETE_ALBUM"
const ADD_SONG = "ADD_SONG"
const UPDATE_SONG = "UPDATE_SONG"
const DELETE_SONG = "DELETE_SONG"
const LOADING_SEARCH_RESULTS = "LOADING_SEARCH_RESULTS"

export {FETCHED_RESULTS, FETCHED_DATA, FETCHED_ALBUMS, UPDATE_SONG, ADD_SONG,
ADD_ALBUM, LOADING, CLOSE_MODAL, UPDATE_ALBUM, DELETE_ALBUM, DELETE_SONG,
LOADING_SEARCH_RESULTS}
