const FETCHED_RESULTS = "FETCHED_RESULTS"
const FETCHED_DATA = "FETCHED_DATA"
const FETCHED_SONGS = "FETCHED_SONGS"
const CREATE_ALBUM = "CREATE_ALBUM"
const LOADING_DATA = "LOADING_DATA"
const CLOSE_MODAL = "CLOSE_MODAL"
const UPDATE_ALBUM = "UPDATE_ALBUM"
const DELETE_ALBUM = "DELETE_ALBUM"
const CREATE_SONG = "CREATE_SONG"
const UPDATE_SONG = "UPDATE_SONG"
const DELETE_SONG = "DELETE_SONG"
const LOADING_SEARCH_RESULTS = "LOADING_SEARCH_RESULTS"
const UPDATE_TRACKS = "UDPATE_TRACKS"
const LOADING_SONGS = "LOADING_SONGS"

export {FETCHED_RESULTS, FETCHED_DATA, FETCHED_SONGS, UPDATE_SONG, CREATE_SONG,
CREATE_ALBUM, LOADING_DATA, CLOSE_MODAL, UPDATE_ALBUM, DELETE_ALBUM, DELETE_SONG,
LOADING_SEARCH_RESULTS, UPDATE_TRACKS, LOADING_SONGS}
